// 仅测试 console.log 时机问题
import './test-main-console.uts'

import App from './App.uvue'

import { createSSRApp } from 'vue'
export function createApp() {
  const app = createSSRApp(App)
  app.config.errorHandler = (err, vm, info) => {
    console.log(err, vm, info)
  }
  // app.mixin({
  //   onReady() {
  //     setTimeout(() => {
  //       console.log((this as BasePage).$nativePage!.getDomJson())
  //     }, 100)
  //   }
  // })
  return {
    app
  }
}
